# -*- coding: utf-8 -*-
"""portfolio_items_6_9_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ef8xtfyr711h7HC3uuV1wNgXO8Qq5fpp

# Portfolio Items 6–9  
## Students Social Media Addiction dataset
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import statsmodels.api as sm
import statsmodels.formula.api as smf
from scipy.stats import chi2

plt.style.use("ggplot")
pd.set_option("display.max_columns", 200)
pd.set_option("display.width", 120)

df = pd.read_csv("Students Social Media Addiction.csv")

print("Columns in dataset:")
print(df.columns.tolist())

df_main = df[[
    "Age",
    "Gender",
    "Academic_Level",
    "Avg_Daily_Usage_Hours",
    "Sleep_Hours_Per_Night",
    "Affects_Academic_Performance"
]].copy()

print("\nMissing values:")
print(df_main.isnull().sum())

df_main = df_main.dropna()

df_main["academic_affected"] = (
    df_main["Affects_Academic_Performance"] == "Yes"
).astype(int)

df_main["usage_c"] = (
    df_main["Avg_Daily_Usage_Hours"] - df_main["Avg_Daily_Usage_Hours"].mean()
)
df_main["sleep_c"] = (
    df_main["Sleep_Hours_Per_Night"] - df_main["Sleep_Hours_Per_Night"].mean()
)
df_main["usage_sleep_c"] = df_main["usage_c"] * df_main["sleep_c"]

print("\nData shape:", df_main.shape)
print("\nOutcome distribution:")
print(df_main["academic_affected"].value_counts())

print("\nSummary statistics:")
print(df_main[[
    "Age", "Avg_Daily_Usage_Hours", "Sleep_Hours_Per_Night",
    "usage_c", "sleep_c", "usage_sleep_c", "academic_affected"
]].describe())

print("\nCorrelation matrix:")
print(df_main[["Avg_Daily_Usage_Hours", "Sleep_Hours_Per_Night", "Age"]].corr())

df_main["Sleep_Group"] = pd.cut(
    df_main["Sleep_Hours_Per_Night"],
    bins=[0, 5, 7, 10],
    labels=["Low Sleep", "Medium Sleep", "High Sleep"]
)

sns.lmplot(
    data=df_main,
    x="Avg_Daily_Usage_Hours",
    y="academic_affected",
    hue="Sleep_Group",
    height=5,
    aspect=1.5,
    scatter_kws={"alpha": 0.45}
)

plt.title("Academic Impact vs Social Media Usage by Sleep Group")
plt.xlabel("Average Daily Usage Hours")
plt.ylabel("Academic Performance Affected (0/1)")
plt.show()

"""# Item 6 — Regression with an interaction term

"""

item6_model = smf.logit(
    "academic_affected ~ usage_c + sleep_c + usage_sleep_c + Age",
    data=df_main
).fit()

print(item6_model.summary())

item6_results = pd.DataFrame({
    "Coefficient": item6_model.params,
    "p_value": item6_model.pvalues,
    "Odds_Ratio": np.exp(item6_model.params),
    "Direction": np.where(item6_model.params > 0, "Positive", "Negative"),
    "Significant_5pct": item6_model.pvalues < 0.05
})

print("\nItem 6 results table:")
print(item6_results)

usage_range = np.linspace(df_main["usage_c"].min(), df_main["usage_c"].max(), 100)
sleep_levels = [
    df_main["sleep_c"].quantile(0.25),
    df_main["sleep_c"].quantile(0.50),
    df_main["sleep_c"].quantile(0.75)
]
sleep_labels = ["Low Sleep", "Average Sleep", "High Sleep"]

pred_list = []
for sleep_val, label in zip(sleep_levels, sleep_labels):
    temp = pd.DataFrame({
        "usage_c": usage_range,
        "sleep_c": sleep_val,
        "usage_sleep_c": usage_range * sleep_val,
        "Age": df_main["Age"].mean()
    })
    temp["pred_prob"] = item6_model.predict(temp)
    temp["Sleep_Level"] = label
    pred_list.append(temp)

pred_df_item6 = pd.concat(pred_list)

plt.figure(figsize=(8,5))
for label in sleep_labels:
    subset = pred_df_item6[pred_df_item6["Sleep_Level"] == label]
    plt.plot(subset["usage_c"], subset["pred_prob"], linewidth=2, label=label)

plt.xlabel("Centered Daily Social Media Usage")
plt.ylabel("Predicted Probability Academic Performance Affected")
plt.title("Item 6: Predicted Academic Impact by Usage and Sleep")
plt.legend()
plt.show()

"""# Item 7 — Two-model comparison on the same dataset


"""

item7_ols = smf.ols(
    "academic_affected ~ usage_c + sleep_c + usage_sleep_c + Age",
    data=df_main
).fit()

item7_logit = smf.logit(
    "academic_affected ~ usage_c + sleep_c + usage_sleep_c + Age",
    data=df_main
).fit()

print("\n================ OLS MODEL ================")
print(item7_ols.summary())

print("\n================ LOGISTIC MODEL ================")
print(item7_logit.summary())

comparison7 = pd.DataFrame({
    "OLS_coef": item7_ols.params,
    "OLS_pvalue": item7_ols.pvalues,
    "Logit_coef": item7_logit.params,
    "Logit_pvalue": item7_logit.pvalues,
    "Odds_ratio": np.exp(item7_logit.params)
})

comparison7["OLS_direction"] = np.where(comparison7["OLS_coef"] > 0, "Positive", "Negative")
comparison7["Logit_direction"] = np.where(comparison7["Logit_coef"] > 0, "Positive", "Negative")
comparison7["OLS_significant_5pct"] = comparison7["OLS_pvalue"] < 0.05
comparison7["Logit_significant_5pct"] = comparison7["Logit_pvalue"] < 0.05

print("\n================ ITEM 7 COMPARISON TABLE ================")
print(comparison7)

print("\nShort summary:")
print("OLS R-squared:", round(item7_ols.rsquared, 4))
print("Logit pseudo R-squared:", round(item7_logit.prsquared, 4))

df_main["pred_ols"] = item7_ols.predict(df_main)
df_main["pred_logit"] = item7_logit.predict(df_main)

plt.figure(figsize=(6,5))
plt.scatter(df_main["pred_ols"], df_main["pred_logit"], alpha=0.5)
plt.xlabel("OLS Predicted Value")
plt.ylabel("Logistic Predicted Probability")
plt.title("Item 7: OLS vs Logistic Predictions")
plt.show()

"""# Item 8 — Model choice using a likelihood-based approach


"""

item8_model1 = smf.logit(
    "academic_affected ~ usage_c + sleep_c",
    data=df_main
).fit()

item8_model2 = smf.logit(
    "academic_affected ~ usage_c + sleep_c + usage_sleep_c",
    data=df_main
).fit()

item8_model3 = smf.logit(
    "academic_affected ~ usage_c + sleep_c + usage_sleep_c + Age",
    data=df_main
).fit()

comparison8 = pd.DataFrame({
    "Model": ["Baseline", "Interaction", "Extended"],
    "Parameters": [
        int(item8_model1.df_model + 1),
        int(item8_model2.df_model + 1),
        int(item8_model3.df_model + 1)
    ],
    "LogLikelihood": [
        item8_model1.llf,
        item8_model2.llf,
        item8_model3.llf
    ],
    "AIC": [
        item8_model1.aic,
        item8_model2.aic,
        item8_model3.aic
    ],
    "BIC": [
        item8_model1.bic,
        item8_model2.bic,
        item8_model3.bic
    ]
})

print("\n================ ITEM 8 MODEL COMPARISON ================")
print(comparison8)

lr_stat_12 = 2 * (item8_model2.llf - item8_model1.llf)
df_diff_12 = item8_model2.df_model - item8_model1.df_model
p_value_12 = chi2.sf(lr_stat_12, df_diff_12)

print("\nLR test: Baseline vs Interaction")
print("LR statistic:", lr_stat_12)
print("Degrees of freedom:", df_diff_12)
print("p-value:", p_value_12)

lr_stat_23 = 2 * (item8_model3.llf - item8_model2.llf)
df_diff_23 = item8_model3.df_model - item8_model2.df_model
p_value_23 = chi2.sf(lr_stat_23, df_diff_23)

print("\nLR test: Interaction vs Extended")
print("LR statistic:", lr_stat_23)
print("Degrees of freedom:", df_diff_23)
print("p-value:", p_value_23)

best_aic_model = comparison8.loc[comparison8["AIC"].idxmin(), "Model"]
best_bic_model = comparison8.loc[comparison8["BIC"].idxmin(), "Model"]

print("\nBest model according to AIC:", best_aic_model)
print("Best model according to BIC:", best_bic_model)

usage_range = np.linspace(df_main["usage_c"].min(), df_main["usage_c"].max(), 100)
sleep_low = df_main["sleep_c"].quantile(0.25)
sleep_high = df_main["sleep_c"].quantile(0.75)
age_mean = df_main["Age"].mean()

predictions = []
for sleep_level, label in [(sleep_low, "Low Sleep"), (sleep_high, "High Sleep")]:
    temp = pd.DataFrame({
        "usage_c": usage_range,
        "sleep_c": sleep_level,
        "usage_sleep_c": usage_range * sleep_level,
        "Age": age_mean
    })
    temp["baseline"] = item8_model1.predict(temp)
    temp["interaction"] = item8_model2.predict(temp)
    temp["extended"] = item8_model3.predict(temp)
    temp["Sleep"] = label
    predictions.append(temp)

pred_df_item8 = pd.concat(predictions)

plt.figure(figsize=(9,6))
for model_name in ["baseline", "interaction", "extended"]:
    for sleep_label, style in [("Low Sleep", "--"), ("High Sleep", "-")]:
        subset = pred_df_item8[pred_df_item8["Sleep"] == sleep_label]
        plt.plot(
            subset["usage_c"],
            subset[model_name],
            linestyle=style,
            linewidth=2,
            label=f"{model_name.capitalize()} ({sleep_label})"
        )

plt.xlabel("Centered Daily Social Media Usage")
plt.ylabel("Predicted Probability Academic Performance Affected")
plt.title("Item 8: Predicted Probability Comparison Across Models")
plt.legend()
plt.show()

"""# Item 9 — Causal inference using a DAG idea + covariate adjustment


"""

df_item9 = df[[
    "Age",
    "Gender",
    "Academic_Level",
    "Avg_Daily_Usage_Hours",
    "Affects_Academic_Performance"
]].copy().dropna()

df_item9["academic_affected"] = (
    df_item9["Affects_Academic_Performance"] == "Yes"
).astype(int)

median_usage = df_item9["Avg_Daily_Usage_Hours"].median()
df_item9["high_usage"] = (
    df_item9["Avg_Daily_Usage_Hours"] >= median_usage
).astype(int)

print("Median usage:", median_usage)
print("\nPreview:")
print(df_item9[["Avg_Daily_Usage_Hours", "high_usage", "academic_affected"]].head())

raw_means9 = df_item9.groupby("high_usage")["academic_affected"].mean()
print("\nRaw group means:")
print(raw_means9)

item9_crude = smf.ols("academic_affected ~ high_usage", data=df_item9).fit(cov_type="HC3")
print("\n================ ITEM 9 CRUDE MODEL ================")
print(item9_crude.summary())

crude_ate = item9_crude.params["high_usage"]
crude_ci = item9_crude.conf_int().loc["high_usage"]
print("\nCrude effect (difference in means):", crude_ate)
print(f"95% CI: [{crude_ci[0]:.4f}, {crude_ci[1]:.4f}]")

item9_adj = smf.ols(
    "academic_affected ~ high_usage + Age + C(Gender) + C(Academic_Level)",
    data=df_item9
).fit(cov_type="HC3")

print("\n================ ITEM 9 ADJUSTED MODEL ================")
print(item9_adj.summary())

df0 = df_item9.copy()
df0["high_usage"] = 0

df1 = df_item9.copy()
df1["high_usage"] = 1

mean_y0 = item9_adj.predict(df0).mean()
mean_y1 = item9_adj.predict(df1).mean()
ate_item9 = mean_y1 - mean_y0

adj_coef = item9_adj.params["high_usage"]
adj_ci = item9_adj.conf_int().loc["high_usage"]

print("\nAdjusted mean if low usage (T=0):", mean_y0)
print("Adjusted mean if high usage (T=1):", mean_y1)
print("Adjusted treatment effect (ATE):", ate_item9)

print("\nCoefficient on high_usage:", adj_coef)
print(f"95% CI for adjusted treatment effect: [{adj_ci[0]:.4f}, {adj_ci[1]:.4f}]")

